2021-06-29 14:25:17.694239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/python-3.9.2/lib:/lib64:/usr/lib64:/lib:/usr/lib:/usr/lib64/qt-3.3/lib:/opt/slurm/lib:/opt/slurm/lib/slurm
2021-06-29 14:25:17.694282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-06-29 14:25:17.694268: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/python-3.9.2/lib:/lib64:/usr/lib64:/lib:/usr/lib:/usr/lib64/qt-3.3/lib:/opt/slurm/lib:/opt/slurm/lib/slurm
2021-06-29 14:25:17.694294: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
starting readin
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
(80, 127, 1)
Normalizing training data
Traceback (most recent call last):
  File "/work/noaa/da/svarga/anomDetec/AnomDetecEnsem/AnomDetecTemp.py", line 67, in <module>
starting readin
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
(80, 127, 1)
Normalizing training data
Traceback (most recent call last):
  File "/work/noaa/da/svarga/anomDetec/AnomDetecEnsem/AnomDetecTemp.py", line 67, in <module>
    x_train=np.reshape(x_train, [z,127,1])
  File "<__array_function__ internals>", line 5, in reshape
    x_train=np.reshape(x_train, [z,127,1])
  File "<__array_function__ internals>", line 5, in reshape
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/ma/core.py", line 4648, in reshape
    return bound(*args, **kwds)
  File "/apps/python-3.9.2/lib/python3.9/site-packages/numpy/ma/core.py", line 4648, in reshape
    result = self._data.reshape(*s, **kwargs).view(type(self))
ValueError: cannot reshape array of size 10033 into shape (80,127,1)
    result = self._data.reshape(*s, **kwargs).view(type(self))
ValueError: cannot reshape array of size 10033 into shape (80,127,1)
srun: error: Orion-02-67: tasks 0-1: Exited with exit code 1
srun: Terminating job step 2365414.0
